baseURL = 'https://physicslk.netlify.app/'
languageCode = 'en-us'
title = 'Physics Blog'

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
[pagination]
  pagerSize = 12

[params]
  env = 'production'
  title = 'Physics Blog'
  description = 'A blog about physics, mathematics, and scientific exploration'
  keywords = [ 'Physics', 'Mathematics', 'Science', 'Research', 'Education' ]
  author = 'Janith Malinga'
  
  [params.assets]
    disableFingerprinting = false
    disableScrollBarStyle = false
  

  [params.homeInfoParams]
    Title = 'Welcome to Physics Blog'
    Content = 'A space dedicated to exploring physics, mathematics, and scientific discovery. Join me on this journey through the fascinating world of science.'


